# Generated by Django 4.0.5 on 2022-07-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('price_dol', models.IntegerField()),
                ('date', models.DateField()),
                ('price_rub', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='valute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('krs', models.FloatField(default=0)),
            ],
        ),
    ]
